/*************************************************************************
*
* CEWiT CONFIDENTIAL
* __________________
*
* All Rights Reserved © 2012 CEWiT, India
*
* NOTICE: All information contained herein is, and remains the property of Centre of Excellence in Wireless Technology (CEWiT)
* and its suppliers, if any. The intellectual and technical concepts contained herein may be proprietary to CEWiT.
* Unauthorized use, duplication, reverse engineering, any form of redistribution, or use in part or in whole other than by prior,
* express, printed and signed license for use is strictly forbidden.
*/
#ifndef CFTP_H
#define CFTP_H

#include "cTrafficClass.h"
#include "../Others/cPacket.h"
#include "../Others/L2SimConfig.h"


// #define TCP_HEADER 40
// #define INITIAL_CONGESTION_WINDOW 1

/* parameter for log normal distribution (file size)
 * source NGMN document (traffic models) */
// #define LOGNORMAL_MEAN 14.45
// #define LOGNORMAL_VARIANCE 0.35



#define CHUNK_SIZE 2 // 2 packet

// typedef enum _FtpMode
// {
//     FTP_MODE = 0,
//     USER_MODE
// } 
// FtpMode;

/* FTP session status */
typedef enum _FtpSessionState
{
    IN_PROGRESS = 1,
    FINISHED = 2,
} FtpSessionState;

/* State of the user with respect to FTP */
typedef enum _FtpUserState
{
    FTP_INACTIVE = 1,
    FTP_ACTIVE = 2,
} FtpUserState;

typedef enum _eFtpFileSizeType
{
    SMALL_FILE = 1,
    MEDIUM_FILE = 2,
    LARGE_FILE = 3,
} eFtpFileSizeType;

class cFTP : public cTrafficClass
{
private:

    unsigned int mTcpHeaderLen;		/**< TCP header length in IP packet **/
    unsigned int mInitialCongestionWindow;	/**< Initial congestion window for TCP **/
    bool isTCPenabled;
    double mLogNormalMean;		/**< File is lognormal distributed. this gives the mean of this distribution **/
    double mLogNormalStandardDeviation;	/**< this gives standard deviation of the lognormal distribution **/
    int mMaxFileSize,mMinFileSize;
    
    
    double mInterReadTimeLamba;		/**< lambda value of inter read time **/
    double mTCTimeLambda;		/**< lambda value of TC time **/
    double mArrTimeLambda;		/**< User arrival rate (3GPP FTP Model 1) **/
    unsigned int mChunkSize;		/**< number of packet in chunk **/

    unsigned long int mFileSize;	/**< FTP file size in bytes **/
    unsigned int mInterReadDuration;	/**< the elapsed between two FTP sessions **/
    int mTcTime;			/**< this time taken by an ACK packet from US to reach the server and next pack from server to reach base station **/
    unsigned int mWindowSize;		/**< num of packets sent first time a new FTP session is started **/
    unsigned int mMtuSize;		/**< MTU size of the IP packet - it can be either 1500 or 576 **/
    unsigned int mChunkCount;		/**< a Chunk is group of packets (2 in this case). the variable gives gives how many such chuck are available **/
    unsigned int mNumPktPerFile;	/**< number of packet in a file **/
    unsigned int mNumPktRemaining;	/**< at any point in time during the course when the FTP file is being transmitted, the variable indicates the number of FTP packet remaining to be sent **/
//     unsigned int mPktToSendIndx;	/**< this varibale points to the next subframe number when the next FTP chuck must transmitted **/
    unsigned int mNextFtpStartFrame;	/**< this varibale indicate when the next FTP session is supposed to start **/
    unsigned int mNumFtpSessions;	/**< this indicates the total number of FTP session that has finished **/
    unsigned long int mTotalTrafGen;	/**< total number of bytes generated by this FTP app during the period of simulation **/
    int mCurSubFrameNo;

    eFtpFileSizeType mFileSizeType;         /**< Chosen by the simulator user to specify - SMALL, LARGE, or MEDIUM **/

    unsigned int mNumPktsInQ;		/**< number of packets enqueued in this subframe - 0, 1 or 2 **/

    FtpUserState mUserState;		/**< FTP_ACTIVE or FTP_INACTIVE **/
    FtpSessionState mFtpSessionStatus;	/**< IN_PROGRESS or FINISHED**/

//     vector <sPacketSubFrameNoPair> mPacketSubFrameNoPair;
    int mFTPModelType;
    double mInterPktTimeLambda;

public:
    /**
  * @brief
  * VoIP Traffic Generator Constructor.
  * @fn cFTP
  */
    cFTP();

    /**
  * @brief
  * VoIP Traffic Generator Constructor.
  * @fn cFTP
  * @param trafficType
  * Type of Traffic Generator.
  * @param int dest
  * Destination Identification Number
  * @param int src
  * Source Identification Number
  */
//     cFTP(eTrafficType trafficType, int tSrc, int tDest, int tAppId, sL2SimConfig* sSimConfig,int UEId=-1,int eNBId=-1);

    cFTP& operator=(cFTP const& tFTP);
    cFTP(eTrafficType trafficType, string l2SupportFileName, int subframeCnt, int& arrivalTimeFTP);

    cFTP(cTrafficClass& tTrafficClass);

    /**
  * @brief
  * VoIP Traffic Generator Destructor.
  * @fn ~cFTP
  */
    ~cFTP();

    /**
    *@brief
    * FTP traffic generation initialization function.
    * @fn fInitFtp
    */
    void fInitFtp();

    void fInitFtp(sFTPTrafficGeneratorConfig& ftpConfig,double frameDuration);
    void fInitFtp(string l2SupportFileName);

    /**
    *@brief
    * Function called before every FTP session.
    * @fn fSessionInit
    */
    void fSessionInit();

    /**
    * @brief
    * File size generator
    * @fn fGenFileSize
    */
    void fGenFileSize(bool useFixedFileSize);

    /**
    * @brief
    * Function to randomly generate the time between successive FTP session
    * @fn fGenInterReadDuration
    */
    void fGenInterReadDuration();
    int fGetInterReadDuration();

    /**
    * @brief
    * Function which generates the TC time
    * @fn fGenTCTime
    */
    void fGenTCTime();
    
    void fGenTCTimeFor3GPPModel();
    int fGetInterPacketDurationFor3GPPModel();

    /**
    * @brief
    * Function which generates the TC time
    * @fn fGenTCTime
    */
    void fGenMtuSize();
    
    void fGenMtuSizeFor3GPPModel();
    int fGetPacketSizeFor3GPPModel(){return 1500;}

    /**
    * @brief
    * Function which generates the TC time
    * @fn fGenTCTime
    */
    void fGenPacketFromFile(int tEndSubFrameNo);
    
    void fGenPacketFromFileFor3GPPModel(int tEndSubFrameNo);
    void fregen(int subframeCnt, int& arrivalTimeFTP);
    /**
    * @brief
    * Function which get FTP Session
    * @fn fGenFTPSession
    */
    void fGenFTPSession(int tEndSubFrameNo);

    /**
    * @brief
    * Function which get FTP Traffic
    * @fn fGenFTPTraffic
    */
    void fGenFTPTraffic(int tStartSubFrameNo, int tEndSubFrameNo);
    
    void fGenFTPTrafficFor3GPPModel(int tStartSubFrameNo, int tEndSubFrameNo);

    /**
    * @brief
    * Function which generates the traffic depending the sub frame number at which it is called
    * @fn fCallTraffic
    */
//     cPacketQueue fCallTraffic(int tCurSubFrameNum);

    /**
    * @brief
    * Function which adds the generated packet to the queue
    * @fn fEnqueuePktToQueue
    */
//     void fEnqueuePktToQueue(cPacketQueue* tPktQueue, int packetIndx);
    int getNumOfSessions(){return mNumFtpSessions;}
};

#endif // CFTP_H
